#!/bin/bash

if [ -f "./linux.tar.zst" ]; then
  exit
fi

if [ ! -f "/usr/local/bin/clang" ]; then
  echo "Please install clang via llvm.sh"
fi
if [ -z "$(which rustc)" ]; then
  echo "Please install rust"
fi
if [ -z "$(which bindgen)" ]; then
  echo "Please install rust-bindgen"
fi

source "$(dirname "$(realpath "$0")")/lib.sh"

set -e

setup_root_tree linux

cd linux

make LLVM=1 LLVM_PREFIX=/usr/local/bin/ allyesconfig
./scripts/config \
  -d WERROR \
  -d EXPERT \
  -d LOCALVERSION_AUTO \
  -d KERNEL_GZIP \
  -e KERNEL_ZSTD \
  -e PREEMPT \
  -d PREEMPT_LAZY \
  -d COMPILE_TEST \
  -d UAPI_HEADER_TEST \
  -d KUNIT \
  -d ZSMALLOC_STAT \
  -d GPIO_VIRTUSER \
  -d EDAC_DEBUG \
  -d SUNRPC_DEBUG \
  -d DEBUG_CLOSURES \
  -d FTRACE \
  -d PUNIT_ATOM_DEBUG \
  -d KCOV \
  -d DEBUG_KERNEL \
  -d KEXEC_HANDOVER_DEBUGFS \
  -d DEBUG_FS \
  -d BOOT_CONFIG_FORCE \
  -d MODVERSIONS \
  -d RANDSTRUCT_FULL \
  -e RANDSTRUCT_NONE \
  -e RUST \
  -d NO_HZ_IDLE \
  -e NO_HZ_FULL \
  -d NO_HZ \
  -d PSI_DEFAULT_DISABLED \
  -d RCU_EXPERT \
  -d RCU_LAZY_DEFAULT_OFF \
  -d CGROUP_FAVOR_DYNMODS \
  -e MEMCG_V1 \
  -e CPUSETS_V1 \
  -d RT_GROUP_SCHED_DEFAULT_DISABLED \
  -d DEFERRED_STRUCT_PAGE_INIT \
  -e KEXEC_HANDOVER \
  -e KEXEC_HANDOVER_ENABLE_DEFAULT \
  -e LIVEUPDATE \
  -e X86_NATIVE_CPU \
  -d MICROCODE_LATE_LOADING \
  -d EFI_MIXED \
  -d EFI_HANDOVER_PROTOCOL \
  -d HZ_250 \
  -e HZ_1000 \
  -d COMPAT_VDSO \
  -d CMDLINE_BOOL \
  -d PM_USERSPACE_AUTOSLEEP \
  -d BSD_PROCESS_ACCT \
  -d ARCH_MEMORY_PROBE \
  -d PM_DEBUG \
  -d ACPI_DEBUGGER \
  -d ACPI_REV_OVERRIDE_POSSIBLE \
  -d ACPI_EC_DEBUGFS \
  -d ACPI_DEBUG \
  -d NFIT_SECURITY_DEBUG \
  -d ACPI_APEI_ERST_DEBUG \
  -e CPUFREQ_DT_RUST \
  -e X86_AMD_PSTATE_UT \
  -d KPROBES \
  -d STATIC_KEYS_SELFTEST \
  -d STATIC_CALL_SELFTEST \
  -d AUTOFDO_CLANG \
  -d PROPELLER_CLANG \
  -d CFI_PERMISSIVE \
  -d MODULE_FORCE_LOAD \
  -d MODULE_FORCE_UNLOAD \
  -d MODULE_COMPRESS_GZIP \
  -e MODULE_COMPRESS_ZSTD \
  -d MODULE_ALLOW_MISSING_NAMESPACE_IMPORTS \
  -d TRIM_UNUSED_KSYMS \
  -d PARTITION_ADVANCED \
  -d BFQ_CGROUP_DEBUG \
  -d COMPAT_BRK \
  -d DMAPOOL_TEST \
  -d LRU_GEN_STATS \
  -d NUMA_EMU \
  -d ZSWAP_COMPRESSOR_DEFAULT_LZO \
  -e ZSWAP_COMPRESSOR_DEFAULT_ZSTD \
  -d SLUB_STATS \
  -d READ_ONLY_THP_FOR_FS \
  -d NO_PAGE_MAPCOUNT \
  -d DAMON_STAT_ENABLED_DEFAULT \
  -d AF_RXRPC_INJECT_LOSS \
  -d AF_RXRPC_INJECT_RX_DELAY \
  -d AF_RXRPC_DEBUG \
  -d RXPERF \
  -d CEPH_LIB_PRETTYDEBUG \
  -d TLS_TOE \
  -d XFRM_STATISTICS \
  -d IP_FIB_TRIE_STATS \
  -d NETWORK_PHY_TIMESTAMPING \
  -d RDS_DEBUG \
  -d ATM_LANE \
  -d BATMAN_ADV_DEBUG \
  -d IP_VS_DEBUG \
  -d SCTP_DBG_OBJCNT \
  -d NET_ACT_SIMP \
  -d NET_PKTGEN \
  -d CFG80211_DEVELOPER_WARNINGS \
  -d MAC80211_DEBUG_MENU \
  -e NET_9P_DEBUG \
  -d CAIF_DEBUG \
  -d NFC_SIM \
  -d NFC_VIRTUAL_NCI \
  -d PCIEAER_INJECT \
  -d PCI_EPF_TEST \
  -d RAPIDIO_DEBUG \
  -d PREVENT_FIRMWARE_BUILD \
  -d STANDALONE \
  -d TEST_ASYNC_DRIVER_PROBE \
  -d DMA_FENCE_TRACE \
  -d FW_LOADER_DEBUG \
  -e RUST_FW_LOADER_ABSTRACTIONS \
  -d FW_LOADER_USER_HELPER_FALLBACK \
  -d EFI_VARS_PSTORE_DEFAULT_DISABLE \
  -d EFI_TEST \
  -d EFI_DISABLE_RUNTIME \
  -d OVMF_DEBUG_LOG \
  -d MTD_TESTS \
  -d MTD_REDBOOT_PARTS_READONLY \
  -e MTD_PMC551_DEBUG \
  -d MTD_MTDRAM \
  -d MTD_NAND_NANDSIM \
  -d MTD_NAND_DISKONCHIP_PROBE_HIGH \
  -d OF_UNITTEST \
  -d PNP_DEBUG_MESSAGES \
  -d BLK_DEV_NULL_BLK \
  -d ZRAM_DEF_COMP_LZORLE \
  -e ZRAM_DEF_COMP_ZSTD \
  -d DRBD_FAULT_INJECTION \
  -d NVME_VERBOSE_ERRORS \
  -d NVME_TARGET_DEBUGFS \
  -d DUMMY_IRQ \
  -d SGI_GRU_DEBUG \
  -d CB710_DEBUG \
  -d SCSI_CONSTANTS \
  -d SCSI_LOGGING \
  -e AIC7XXX_DEBUG_ENABLE \
  -e AIC7XXX_REG_PRETTY_PRINT \
  -e AIC79XX_DEBUG_ENABLE \
  -e AIC79XX_REG_PRETTY_PRINT \
  -e AIC94XX_DEBUG \
  -d SCSI_MVSAS_DEBUG \
  -d SCSI_IPR_TRACE \
  -e TCM_QLA2XXX_DEBUG \
  -d SCSI_DEBUG \
  -d ATA_VERBOSE_ERROR \
  -d BCACHE_DEBUG \
  -d DM_DEBUG \
  -d DM_DUST \
  -d FUSION_LOGGING \
  -d DUMMY \
  -d WIREGUARD_DEBUG \
  -d ATM_DUMMY \
  -d ATM_ENI_DEBUG \
  -e ATM_IDT77252_DEBUG \
  -d ATM_IA_DEBUG \
  -d SUNDANCE_MMIO \
  -d TSNEP_SELFTESTS \
  -d NFP_DEBUG \
  -d STMMAC_SELFTESTS \
  -d CAN_DUMMY \
  -d CAN_DEBUG_DEVICES \
  -d ATH_DEBUG \
  -e ATH5K_DEBUG \
  -e ATH6KL_DEBUG \
  -d ATH10K_DEBUG \
  -e WCN36XX_DEBUGFS \
  -e ATH11K_DEBUG \
  -e ATH12K_DEBUG \
  -e B43_DEBUG \
  -e B43LEGACY_DEBUG \
  -d BRCMDBG \
  -d IPW2100_DEBUG \
  -d IPW2200_DEBUG \
  -d LIBIPW_DEBUG \
  -d LIBERTAS_DEBUG \
  -d LIBERTAS_THINFIRM_DEBUG \
  -e ZD1211RW_DEBUG \
  -d MAC80211_HWSIM \
  -d IEEE802154_HWSIM \
  -e I2C_STUB \
  -e I2C_SLAVE_TESTUNIT \
  -e I2C_DEBUG_CORE \
  -e I2C_DEBUG_ALGO \
  -e I2C_DEBUG_BUS \
  -d SPI_LOOPBACK_TEST \
  -d PPS_DEBUG \
  -d PPS_CLIENT_KTIMER \
  -d PPS_GENERATOR_DUMMY \
  -d GPIO_MOCKUP \
  -d GPIO_SIM \
  -d POWER_SUPPLY_DEBUG \
  -d TEST_POWER \
  -d HWMON_DEBUG_CHIP \
  -d WATCHDOG_NOWAYOUT \
  -d BCMA_DEBUG \
  -d REGULATOR_DEBUG \
  -d MEDIA_TEST_SUPPORT \
  -d VIDEO_ADV_DEBUG \
  -d DVB_ULE_DEBUG \
  -e VIDEO_PVRUSB2_DEBUGIFC \
  -e DVB_B2C2_FLEXCOP_USB_DEBUG \
  -d PANEL_CHANGE_MESSAGE \
  --set-str DRM_PANIC_SCREEN kmsg \
  -d NOUVEAU_DEBUG_PUSH \
  -d DRM_DEBUG_MM \
  -d FB_NVIDIA_DEBUG \
  -d FB_RIVA_DEBUG \
  -d FB_RADEON_DEBUG \
  -d LOGO \
  -d DRM_ACCEL_IVPU_DEBUG \
  -d SND_VERBOSE_PROCFS \
  -d SND_DEBUG \
  -d SND_SEQ_DUMMY \
  -d SND_DUMMY \
  -d SND_TEST_COMPONENT \
  -d USB_OTG_DISABLE_EXTERNAL_HUB \
  -d USB_HCD_TEST_MODE \
  -d USB_STORAGE_DEBUG \
  -d USBIP_DEBUG \
  -d MUSB_PIO_ONLY \
  -e USB_DWC2_DEBUG \
  -d USB_TEST \
  -d USB_LINK_LAYER_TEST \
  -d USB_SERIAL_DEBUG \
  -d USB_GADGET_DEBUG_FILES \
  -d USB_DUMMY_HCD \
  -d USB_ZERO_HNPTEST \
  -d USB_G_DBGP \
  -d MMC_TEST \
  -d MMC_DEBUG \
  -d MEMSTICK_DEBUG \
  -d MEMSTICK_UNSAFE_RESUME \
  -d SPEAKUP_SYNTH_DUMMY \
  -d RTC_DEBUG \
  -d RTC_DRV_TEST \
  -d DMADEVICES_DEBUG \
  -d DMATEST \
  -d DMABUF_DEBUG \
  -d DMABUF_SELFTESTS \
  -d VIRTIO_DEBUG \
  -d COMEDI_DEBUG \
  -d COMEDI_TESTS \
  -d COMEDI_TEST \
  -d AMD_PMF_DEBUG \
  -d INTEL_TELEMETRY \
  -d THINKPAD_ACPI_DEBUGFACILITIES \
  -d THINKPAD_ACPI_DEBUG \
  -d IOMMU_DEFAULT_DMA_LAZY \
  -e IOMMU_DEFAULT_DMA_STRICT \
  -d DEBUG_GENERIC_PT \
  -d IIO_SIMPLE_DUMMY \
  -d NTB_PINGPONG \
  -d NTB_TOOL \
  -d NTB_MSI_TEST \
  -e USB4_DEBUGFS_WRITE \
  -d NVDIMM_SECURITY_TEST \
  -d STM_DUMMY \
  -e EXT4_DEBUG \
  -e JBD2_DEBUG \
  -d JFS_DEBUG \
  -d XFS_DEBUG \
  -e OCFS2_DEBUG_MASKLOG \
  -d BTRFS_DEBUG \
  -d BTRFS_EXPERIMENTAL \
  -d NETFS_DEBUG \
  -d CACHEFILES_DEBUG \
  -d CACHEFILES_ERROR_INJECTION \
  -d BEFS_DEBUG \
  -d UFS_DEBUG \
  -d NFS_USE_LEGACY_DNS \
  -d CIFS_DEBUG \
  -d DLM_DEBUG \
  -d SECURITY_SELINUX_DEBUG \
  -d SECURITY_TOMOYO_INSECURE_BUILTIN_SETTING \
  -d SECURITY_APPARMOR_DEBUG_ASSERTS \
  -d SECURITY_APPARMOR_DEBUG_MESSAGES \
  -d INIT_STACK_ALL_PATTERN \
  -e INIT_STACK_ALL_ZERO \
  -e CRYPTO_KRB5_SELFTESTS \
  -d CRYPTO_BENCHMARK \
  -e RANDOM32_SELFTEST \
  -d DMA_API_DEBUG \
  -d LWQ_TEST \
  -e PROVIDE_OHCI1394_DMA_INIT \
  -d DEBUG_BUGVERBOSE_DETAILED \
  -d UBSAN \
  -d KASAN \
  -d KFENCE \
  -d SLUB_DEBUG_ON \
  -d DEBUG_RODATA_TEST \
  -d DEBUG_VM_PGTABLE \
  -d TEST_LOCKUP \
  -d SCHEDSTATS \
  -d WW_MUTEX_SELFTEST \
  -d RCU_CPU_STALL_CPUTIME \
  -d SAMPLES \
  -d EFI_PGT_DUMP \
  -d RUNTIME_TESTING_MENU \
  -d RUST_OVERFLOW_CHECKS

make LLVM=1 LLVM_PREFIX=/usr/local/bin/ olddefconfig
make LLVM=1 LLVM_PREFIX=/usr/local/bin/ -j$(nproc --all)

make LLVM=1 LLVM_PREFIX=/usr/local/bin/ INSTALL_MOD_PATH=$(realpath ../linux-inst) modules_install
make LLVM=1 LLVM_PREFIX=/usr/local/bin/ INSTALL_HDR_PATH=$(realpath ../linux-inst/usr) headers_install
cp ./arch/x86/boot/bzImage ../linux-inst/boot/vmlinuz

cd ..
package_install linux